import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import streamlit as st
import uuid
from workflow.session import ContentRevisionRequest, SessionPhase, SessionManager

st.set_page_config(page_title="Post-Prose Review", layout="wide")
st.title("Post-Prose Review")
st.caption("Review prose generated from the locked spec — log any content revision requests")

st.info(
    "**Key metric:** How many content revision requests are raised after prose is generated "
    "from the locked spec? Fewer content revisions = the spec-first alignment worked. "
    "Formatting and language changes are expected; log only CONTENT changes here."
)

session = st.session_state.get("alignment_session")
if not session:
    st.warning("No active session.")
    st.stop()

mgr = SessionManager()
spec = st.session_state.get("current_spec")
section_ids = ([s.section_id for s in spec.sections] if spec else
               ["background_rationale", "phase2_results_summary",
                "proposed_phase3_design", "cardiovascular_safety", "regulatory_questions"])
roles = [p.role for p in session.participants]

# In a full integration, prose would be generated here from the handoff package
# and displayed for review. For POC, prose is simulated.
st.subheader("Simulated Generated Prose")
st.caption("(In production: prose generated by Medical Writing Track 2 from the locked spec)")
st.text_area("Generated prose excerpt (simulated):", value="""
Background and Rationale

Aleniglipron is a GLP-1 receptor agonist under investigation for the treatment of obesity.
The Phase 2 ACCESS II study demonstrated clinically meaningful and statistically significant
reductions in body weight in adults with obesity at Week 36...

[Additional sections generated from locked content specification...]
""", height=200, disabled=True)

st.divider()
st.subheader("Log Content Revision Requests")
st.caption("Log only requests that require CONTENT changes. Do not log formatting "
           "or language preferences.")

num_requests = st.number_input("Number of revision requests to log:",
                               min_value=0, max_value=20, value=0)

revision_requests = []
for i in range(int(num_requests)):
    with st.expander(f"Revision Request {i + 1}", expanded=True):
        col1, col2 = st.columns(2)
        with col1:
            section = st.selectbox("Section:", section_ids, key=f"sec_{i}")
            change_type = st.selectbox("Change type:",
                                       ["content_change", "formatting", "language"],
                                       key=f"type_{i}")
            requesting_role = st.selectbox("Requested by:", roles, key=f"role_{i}")
        with col2:
            description = st.text_area("Description of required change:", key=f"desc_{i}")

        if description:
            revision_requests.append(ContentRevisionRequest(
                request_id=f"rev_{uuid.uuid4().hex[:6]}",
                requesting_role=requesting_role,
                section_id=section,
                description=description,
                change_type=change_type,
            ))

if st.button("Submit Post-Prose Review"):
    session.content_revision_requests.extend(revision_requests)
    session.phase = SessionPhase.POST_PROSE_REVIEW
    mgr.save(session)
    content_changes = [r for r in revision_requests if r.change_type == "content_change"]
    st.success(f"Review submitted. {len(revision_requests)} total requests logged "
               f"({len(content_changes)} content changes).")
    st.info("Navigate to **Survey** to complete your post-session survey.")
