"""
CI analysis / presentation helpers for the v2 UX.

These derive the strategic read-outs the redesigned CI Review, Message Map and
Draft Bridge pages render: the achievability ceiling table, the strategic
insight bar, per-comparator claim detail with adopt/adapt/skip signals, and the
synchronized reference→proposed diff rows.

The per-section "plan" (which action a section calls for against the Foundayo
comparator, and the colour that encodes it) is a curated demo mapping for the
aleniglipron / obesity / Foundayo combination — in production this would be
generated by the message map LLM. The data underneath it (precedent counts,
claim text, regulatory notes) is read live from the CI twin.
"""
from labeling.labeling_models import CompetitiveIntelligenceTwin

# The five CCDS sections surfaced in the v2 achievability table + diff views.
CCDS_SECTIONS_5 = [
    "Indications and Usage",
    "Dosage and Administration",
    "Clinical Studies",
    "Warnings and Precautions",
    "Adverse Reactions",
]

# action -> highlight colour (purple adopt, amber adapt, blue new, red diverge/skip)
ACTION_COLOR = {
    "adopt": "purple",
    "adapt": "amber",
    "new": "blue",
    "skip": "red",
}

# Curated section plan for the Foundayo→aleniglipron demo.
SECTION_PLAN = {
    "Indications and Usage": {
        "action": "adopt", "our_data": "Ready", "signal": "HIGH",
        "delta": "",
    },
    "Dosage and Administration": {
        "action": "skip", "our_data": "Route TBD", "signal": "GAP",
        "delta": "Foundayo is an oral nonpeptide GLP-1 agonist. Aleniglipron route "
                 "and titration are not finalised — dosing language cannot be adopted yet.",
    },
    "Clinical Studies": {
        "action": "adapt", "our_data": "Ph2 only", "signal": "MED",
        "delta": "Responder-analysis structure is class standard, but aleniglipron "
                 "values are Phase 2 only — final label language requires Phase 3 data.",
    },
    "Warnings and Precautions": {
        "action": "adapt", "our_data": "TBC", "signal": "MED",
        "delta": "Foundayo omits the class boxed warning (no rodent thyroid C-cell tumors). "
                 "Aleniglipron's nonclinical findings must confirm the same result before "
                 "the warning variant can be chosen.",
    },
    "Adverse Reactions": {
        "action": "adopt", "our_data": "Ready", "signal": "HIGH",
        "delta": "GI adverse-reaction profile is class standard. Confirm whether "
                 "aleniglipron shares Foundayo's alopecia signal before finalising.",
    },
}

SIGNAL_COLOR = {"HIGH": "green", "MED": "orange", "GAP": "red"}


def _claims_in_section(ci_twin, section):
    return [c for c in ci_twin.approved_claims if c.label_section == section]


def achievability_table(ci_twin: CompetitiveIntelligenceTwin, content_twin=None,
                        signal_overrides: dict = None) -> list:
    """One row per CCDS section: precedent count, our-data readiness, overall signal.
    signal_overrides (section -> signal) lets the reviewer override the machine read."""
    signal_overrides = signal_overrides or {}
    rows = []
    for section in CCDS_SECTIONS_5:
        plan = SECTION_PLAN.get(section, {"our_data": "—", "signal": "GAP"})
        signal = signal_overrides.get(section, plan["signal"])
        rows.append({
            "section": section,
            "precedents": len(_claims_in_section(ci_twin, section)),
            "our_data": plan["our_data"],
            "signal": signal,
            "overridden": section in signal_overrides,
        })
    return rows


def strategic_insight(ci_twin: CompetitiveIntelligenceTwin,
                      program_name: str = "aleniglipron",
                      reference_drug: str = "orforglipron (Foundayo)") -> str:
    """Plain-English synthesis of what the CI landscape means for the program."""
    ind_drugs = {c.drug_name for c in _claims_in_section(ci_twin, "Indications and Usage")}
    n_ind = len(ind_drugs)
    parts = []
    if n_ind >= 2:
        parts.append(
            f"{n_ind} obesity GLP-1 approvals have converged on identical indication "
            f"language — adopt verbatim, risk is negligible."
        )
    warn = _claims_in_section(ci_twin, "Warnings and Precautions")
    foundayo_warn = next((c for c in warn if reference_drug.split()[0].lower() in c.drug_name.lower()), None)
    if foundayo_warn:
        parts.append(
            f"Boxed warning will require adaptation: {reference_drug}'s nonpeptide mechanism "
            f"produced no rodent thyroid C-cell tumors, so it omits the class boxed warning; "
            f"{program_name}'s nonclinical findings must determine which warning variant applies."
        )
    if _claims_in_section(ci_twin, "Dosage and Administration"):
        parts.append(
            f"Dosage and Administration is a divergence: {reference_drug} is oral, while "
            f"{program_name}'s route is not yet finalised — skip until confirmed."
        )
    return " ".join(parts) or (
        f"Competitive landscape for {program_name} in {ci_twin.indication_class} is being assembled."
    )


def comparator_detail(ci_twin: CompetitiveIntelligenceTwin, drug_name: str,
                      action_overrides: dict = None) -> list:
    """Per-section claim detail for one comparator drug, with adopt/adapt/skip signal.
    action_overrides (section -> action) lets the reviewer change the recommendation."""
    action_overrides = action_overrides or {}
    out = []
    for section in CCDS_SECTIONS_5:
        claims = [c for c in _claims_in_section(ci_twin, section)
                  if c.drug_name == drug_name]
        if not claims:
            continue
        plan = SECTION_PLAN.get(section, {"action": "adapt", "delta": ""})
        action = action_overrides.get(section, plan["action"])
        for c in claims:
            out.append({
                "section": section,
                "claim_text": c.claim_text,
                "action": action,
                "color": ACTION_COLOR.get(action, "gray"),
                "delta": plan["delta"],
                "regulatory_notes": c.regulatory_notes,
                "overridden": section in action_overrides,
            })
    return out


def list_comparators(ci_twin: CompetitiveIntelligenceTwin) -> list:
    """Distinct comparator drug names present in the CI twin (reference first if known)."""
    names = []
    for c in ci_twin.approved_claims:
        if c.drug_name not in names:
            names.append(c.drug_name)
    # Surface Foundayo first if present
    names.sort(key=lambda n: (0 if "foundayo" in n.lower() else 1, n))
    return names


def reference_sections(ci_twin: CompetitiveIntelligenceTwin,
                       reference_drug: str, message_map=None,
                       action_overrides: dict = None) -> list:
    """
    Synchronized reference→proposed rows for the Message Map / Draft Bridge views.
    One entry per CCDS section: the reference comparator's text, the recommended
    action + colour, the delta note, and the proposed message-map claim (if any).
    """
    # Index message-map claims by section (first claim per section)
    mm_by_section = {}
    if message_map is not None:
        for claim in message_map.claims:
            mm_by_section.setdefault(claim.label_section, claim)

    action_overrides = action_overrides or {}
    rows = []
    for section in CCDS_SECTIONS_5:
        plan = SECTION_PLAN.get(section, {"action": "adapt", "delta": "", "signal": "MED"})
        action = action_overrides.get(section, plan["action"])
        ref_claims = _claims_in_section(ci_twin, section)
        ref = next((c for c in ref_claims if c.drug_name == reference_drug),
                   ref_claims[0] if ref_claims else None)
        mm_claim = mm_by_section.get(section)
        rows.append({
            "section": section,
            "action": action,
            "color": ACTION_COLOR.get(action, "gray"),
            "signal": plan.get("signal", "MED"),
            "delta": plan["delta"],
            "reference_text": ref.claim_text if ref else "(no approved precedent for this section)",
            "reference_drug": ref.drug_name if ref else reference_drug,
            "proposed_text": mm_claim.proposed_claim_text if mm_claim else "",
            "claim_id": mm_claim.claim_id if mm_claim else None,
            "is_gap": mm_claim.is_gap if mm_claim else False,
        })
    return rows
